initialization
setUp

	sunday := (GregorianDay named: 'Sunday' positionInWeek: 1).
	monday := (GregorianDay named: 'Monday' positionInWeek: 2).
	tuesday := (GregorianDay named: 'Tuesday' positionInWeek: 3).
	wednesday := (GregorianDay named: 'Wednesday' positionInWeek: 4).
	thursday := (GregorianDay named: 'Thursday' positionInWeek: 5).
	friday := (GregorianDay named: 'Friday' positionInWeek: 6).
	saturday := (GregorianDay named: 'Saturday' positionInWeek: 7)