test comparing
testEqual

	self assert: GregorianDay monday = GregorianDay monday.
	self assert: GregorianDay tuesday = GregorianDay tuesday.
	self assert: GregorianDay wednesday = GregorianDay wednesday.
	self assert: GregorianDay thursday = GregorianDay thursday.
	self assert: GregorianDay friday = GregorianDay friday.
	self assert: GregorianDay saturday = GregorianDay saturday.
	self assert: GregorianDay sunday = GregorianDay sunday 
	