initialization
setUp

	december31Of2003 := GregorianDateTime
		date: (FixedGregorianDate yearNumber: 2003 monthNumber: 12 dayNumber: 31)
		timeOfDay: (TimeOfDay  hours: 00).
	december31Of2003On23Hours59Minutes59Seconds := GregorianDateTime
		date: (FixedGregorianDate yearNumber: 2003 monthNumber: 12 dayNumber: 31)
		timeOfDay: (TimeOfDay  hours: 23 minutes: 59 seconds: 59).
	januaryFirstOf2004 := GregorianDateTime
		date: (FixedGregorianDate yearNumber: 2004 monthNumber: 01 dayNumber: 01)
		timeOfDay: (TimeOfDay  hours: 00).
	januaryFirstOf2004On00Hours00Minutes01Seconds := GregorianDateTime
		date: (FixedGregorianDate yearNumber: 2004 monthNumber: 01 dayNumber: 01)
		timeOfDay: (TimeOfDay  hours: 00 minutes: 00 seconds: 01).
	januaryFirstOf2004On03Hours := GregorianDateTime
		date: (FixedGregorianDate yearNumber: 2004 monthNumber: 01 dayNumber: 01)
		timeOfDay: (TimeOfDay  hours: 03).
	januaryFirstOf2004On23Hours59Minutes58Seconds := GregorianDateTime
		date: (FixedGregorianDate yearNumber: 2004 monthNumber: 01 dayNumber: 01)
		timeOfDay: (TimeOfDay  hours: 23 minutes: 59 seconds: 58).
	januaryFirstOf2004On23Hours59Minutes59Seconds := GregorianDateTime
		date: (FixedGregorianDate yearNumber: 2004 monthNumber: 01 dayNumber: 01)
		timeOfDay: (TimeOfDay  hours: 23 minutes: 59 seconds: 59).
	januarySecondOf2004 := GregorianDateTime
		date: (FixedGregorianDate yearNumber: 2004 monthNumber: 01 dayNumber: 02)
		timeOfDay: (TimeOfDay  hours: 00).
	januarySecondOf2004On00Hours00Minutes01Seconds := GregorianDateTime
		date: (FixedGregorianDate yearNumber: 2004 monthNumber: 01 dayNumber: 02)
		timeOfDay: (TimeOfDay  hours: 00 minutes: 00 seconds: 01).
	januarySecondOf2004On23Hours := GregorianDateTime
		date: (FixedGregorianDate yearNumber: 2004 monthNumber: 01 dayNumber: 02)
		timeOfDay: (TimeOfDay  hours: 23).
	januarySecondOf2004On23Hours59Minutes59Seconds := GregorianDateTime
		date: (FixedGregorianDate yearNumber: 2004 monthNumber: 01 dayNumber: 02)
		timeOfDay: (TimeOfDay  hours: 23 minutes: 59 seconds: 59).
	januaryThirdOf2004 := GregorianDateTime
		date: (FixedGregorianDate yearNumber: 2004 monthNumber: 01 dayNumber: 03)
		timeOfDay: (TimeOfDay  hours: 00)