initialization
initializeCommonObjects

	self initializeDays.
	self initializeGlobalVariables.
	self initializeMinusOneDay.
	self initializeZeroDays.
	self initializeOneDay.
	self initializeTwoDays.
	self initializeSevenDays.
	self initializeTwentyEightDays.
	self initializeTwentyNineDays.
	self initializeThirtyDays.
	self initializeThirtyOneDays.
	self initializeThreeHundredSixtyDays.
	self initializeThreeHundredSixtyFiveDays.
	self initializeThreeHundredSixtySixDays