initialization
setUp

	january := GregorianMonth january.
	february := GregorianMonth february.
	march := GregorianMonth march.
	april := GregorianMonth april.
	may := GregorianMonth may.
	june := GregorianMonth june.
	july := GregorianMonth july.
	august := GregorianMonth august.
	september := GregorianMonth september.
	october := GregorianMonth october.
	november := GregorianMonth november.
	december := GregorianMonth december