test day of month creation
testDayOfMonthCreation
	
	self assert: GregorianMonth january first = (GregorianDayOfMonth monthNumber: 1 dayNumber: 1).
	self assert: GregorianMonth january second = (GregorianDayOfMonth monthNumber: 1 dayNumber: 2).
	self assert: GregorianMonth january third = (GregorianDayOfMonth monthNumber: 1 dayNumber: 3).
	self assert: GregorianMonth january fourth = (GregorianDayOfMonth monthNumber: 1 dayNumber: 4).
	self assert: GregorianMonth january fifth = (GregorianDayOfMonth monthNumber: 1 dayNumber: 5).
	self assert: GregorianMonth january sixth = (GregorianDayOfMonth monthNumber: 1 dayNumber: 6).
	self assert: GregorianMonth january seventh = (GregorianDayOfMonth monthNumber: 1 dayNumber: 7).
	self assert: GregorianMonth january eighth = (GregorianDayOfMonth monthNumber: 1 dayNumber: 8).
	self assert: GregorianMonth january ninth = (GregorianDayOfMonth monthNumber: 1 dayNumber: 9).
	self assert: GregorianMonth january tenth = (GregorianDayOfMonth monthNumber: 1 dayNumber: 10).
	self assert: GregorianMonth january eleventh = (GregorianDayOfMonth monthNumber: 1 dayNumber: 11).
	self assert: GregorianMonth january twelfth = (GregorianDayOfMonth monthNumber: 1 dayNumber: 12).
	self assert: GregorianMonth january thirteenth = (GregorianDayOfMonth monthNumber: 1 dayNumber: 13).
	self assert: GregorianMonth january fourteenth = (GregorianDayOfMonth monthNumber: 1 dayNumber: 14).
	self assert: GregorianMonth january fifteenth = (GregorianDayOfMonth monthNumber: 1 dayNumber: 15).
	self assert: GregorianMonth january sixteenth = (GregorianDayOfMonth monthNumber: 1 dayNumber: 16).
	self assert: GregorianMonth january seventeenth = (GregorianDayOfMonth monthNumber: 1 dayNumber: 17).
	self assert: GregorianMonth january eighteenth = (GregorianDayOfMonth monthNumber: 1 dayNumber: 18).
	self assert: GregorianMonth january nineteenth = (GregorianDayOfMonth monthNumber: 1 dayNumber: 19).
	self assert: GregorianMonth january twentieth = (GregorianDayOfMonth monthNumber: 1 dayNumber: 20).
	self assert: GregorianMonth january twentyfirst = (GregorianDayOfMonth monthNumber: 1 dayNumber: 21).
	self assert: GregorianMonth january twentysecond = (GregorianDayOfMonth monthNumber: 1 dayNumber: 22).
	self assert: GregorianMonth january twentythird = (GregorianDayOfMonth monthNumber: 1 dayNumber: 23).
	self assert: GregorianMonth january twentyfourth = (GregorianDayOfMonth monthNumber: 1 dayNumber: 24).
	self assert: GregorianMonth january twentyfifth = (GregorianDayOfMonth monthNumber: 1 dayNumber: 25).
	self assert: GregorianMonth january twentysixth = (GregorianDayOfMonth monthNumber: 1 dayNumber: 26).
	self assert: GregorianMonth january twentyseventh = (GregorianDayOfMonth monthNumber: 1 dayNumber: 27).
	self assert: GregorianMonth january twentyeighth = (GregorianDayOfMonth monthNumber: 1 dayNumber: 28).
	self assert: GregorianMonth january twentyninth = (GregorianDayOfMonth monthNumber: 1 dayNumber: 29)