test
testGlobalVariables

	self assert: January = GregorianMonth january.
	self assert: February= GregorianMonth february.
	self assert: March = GregorianMonth march.
	self assert: April = GregorianMonth april.
	self assert: May = GregorianMonth may.
	self assert: June = GregorianMonth june.
	self assert: July = GregorianMonth july.
	self assert: August = GregorianMonth august.
	self assert: September = GregorianMonth september.
	self assert: October = GregorianMonth october.
	self assert: November = GregorianMonth november.
	self assert: December = GregorianMonth december